gmail_username: 'GetTradiesnz@gmail.com'
gmail_password: 'gtgtgt2015'

api_key: 'key-4dc65f175f9fa9d43b65311d69e434b3'
domain: 'sandbox882de99f355540eebe8df025a26f8cee.mailgun.org'
username: 'postmaster@sandbox882de99f355540eebe8df025a26f8cee.mailgun.org'
password: 'gtgtgt2015'
